CREATE TABLE `USER` (
  `ID` VARCHAR(255) NOT NULL,
  `CREATED_DATE` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `LAST_MODIFIED_DATE` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `EMAIL` VARCHAR(255) NOT NULL,
  `PASSWORD` TEXT NOT NULL,
  `SHARED_ALL_LIBRARIES` BOOLEAN NOT NULL DEFAULT 1,
  `AGE_RESTRICTION` INT,
  `AGE_RESTRICTION_ALLOW_ONLY` BOOLEAN,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `ANNOUNCEMENTS_READ` (
  `USER_ID` VARCHAR(255) NOT NULL,
  `ANNOUNCEMENT_ID` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`USER_ID`, `ANNOUNCEMENT_ID`),
  FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `AUTHENTICATION_ACTIVITY` (
  `USER_ID` VARCHAR(255),
  `EMAIL` TEXT,
  `IP` TEXT,
  `USER_AGENT` TEXT,
  `SUCCESS` BOOLEAN NOT NULL,
  `ERROR` TEXT,
  `DATE_TIME` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `SOURCE` TEXT,
  `API_KEY_ID` TEXT,
  `API_KEY_COMMENT` TEXT,
  FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `LIBRARY` (
  `ID` VARCHAR(255) NOT NULL,
  `CREATED_DATE` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `LAST_MODIFIED_DATE` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `NAME` TEXT NOT NULL,
  `ROOT` TEXT NOT NULL,
  `IMPORT_COMICINFO_BOOK` BOOLEAN NOT NULL DEFAULT 1,
  `IMPORT_COMICINFO_SERIES` BOOLEAN NOT NULL DEFAULT 1,
  `IMPORT_COMICINFO_COLLECTION` BOOLEAN NOT NULL DEFAULT 1,
  `IMPORT_EPUB_BOOK` BOOLEAN NOT NULL DEFAULT 1,
  `IMPORT_EPUB_SERIES` BOOLEAN NOT NULL DEFAULT 1,
  `SCAN_FORCE_MODIFIED_TIME` BOOLEAN NOT NULL DEFAULT 0,
  `SCAN_STARTUP` BOOLEAN NOT NULL DEFAULT 0,
  `IMPORT_LOCAL_ARTWORK` BOOLEAN NOT NULL DEFAULT 1,
  `IMPORT_COMICINFO_READLIST` BOOLEAN NOT NULL DEFAULT 1,
  `IMPORT_BARCODE_ISBN` BOOLEAN NOT NULL DEFAULT 1,
  `CONVERT_TO_CBZ` BOOLEAN NOT NULL DEFAULT 0,
  `REPAIR_EXTENSIONS` BOOLEAN NOT NULL DEFAULT 0,
  `EMPTY_TRASH_AFTER_SCAN` BOOLEAN NOT NULL DEFAULT 0,
  `IMPORT_MYLAR_SERIES` BOOLEAN NOT NULL DEFAULT 1,
  `SERIES_COVER` TEXT NOT NULL,
  `UNAVAILABLE_DATE` DATETIME(6),
  `HASH_FILES` BOOLEAN NOT NULL DEFAULT true,
  `HASH_PAGES` BOOLEAN NOT NULL DEFAULT 0,
  `ANALYZE_DIMENSIONS` BOOLEAN NOT NULL DEFAULT 1,
  `IMPORT_COMICINFO_SERIES_APPEND_VOLUME` BOOLEAN NOT NULL DEFAULT 1,
  `ONESHOTS_DIRECTORY` TEXT,
  `SCAN_CBX` BOOLEAN NOT NULL DEFAULT 1,
  `SCAN_PDF` BOOLEAN NOT NULL DEFAULT 1,
  `SCAN_EPUB` BOOLEAN NOT NULL DEFAULT 1,
  `SCAN_INTERVAL` TEXT NOT NULL,
  `SCAN_MOBI` BOOLEAN NOT NULL DEFAULT 1,
  `HASH_KOREADER` BOOLEAN NOT NULL DEFAULT 0,
  `AD_PAGES_DETECTOR` BOOLEAN NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `SERIES` (
  `ID` VARCHAR(255) NOT NULL,
  `CREATED_DATE` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `LAST_MODIFIED_DATE` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `FILE_LAST_MODIFIED` DATETIME(6) NOT NULL,
  `NAME` TEXT NOT NULL,
  `URL` TEXT NOT NULL,
  `LIBRARY_ID` VARCHAR(255) NOT NULL,
  `BOOK_COUNT` INT NOT NULL DEFAULT 0,
  `DELETED_DATE` DATETIME(6),
  `oneshot` BOOLEAN NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`),
  FOREIGN KEY (`LIBRARY_ID`) REFERENCES `LIBRARY` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `BOOK` (
  `ID` VARCHAR(255) NOT NULL,
  `CREATED_DATE` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `LAST_MODIFIED_DATE` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `FILE_LAST_MODIFIED` DATETIME(6) NOT NULL,
  `NAME` TEXT NOT NULL,
  `URL` TEXT NOT NULL,
  `SERIES_ID` VARCHAR(255) NOT NULL,
  `FILE_SIZE` INT NOT NULL DEFAULT 0,
  `NUMBER` INT NOT NULL DEFAULT 0,
  `LIBRARY_ID` VARCHAR(255) NOT NULL,
  `FILE_HASH` TEXT NOT NULL,
  `DELETED_DATE` DATETIME(6),
  `oneshot` BOOLEAN NOT NULL DEFAULT 0,
  `FILE_HASH_KOREADER` TEXT NOT NULL,
  PRIMARY KEY (`ID`),
  FOREIGN KEY (`SERIES_ID`) REFERENCES `SERIES` (`ID`),
  FOREIGN KEY (`LIBRARY_ID`) REFERENCES `LIBRARY` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `BOOK_METADATA` (
  `CREATED_DATE` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `LAST_MODIFIED_DATE` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `NUMBER` TEXT NOT NULL,
  `NUMBER_LOCK` BOOLEAN NOT NULL DEFAULT 0,
  `NUMBER_SORT` DOUBLE NOT NULL,
  `NUMBER_SORT_LOCK` BOOLEAN NOT NULL DEFAULT 0,
  `RELEASE_DATE` DATETIME(6),
  `RELEASE_DATE_LOCK` BOOLEAN NOT NULL DEFAULT 0,
  `SUMMARY` TEXT NOT NULL,
  `SUMMARY_LOCK` BOOLEAN NOT NULL DEFAULT 0,
  `TITLE` TEXT NOT NULL,
  `TITLE_LOCK` BOOLEAN NOT NULL DEFAULT 0,
  `AUTHORS_LOCK` BOOLEAN NOT NULL DEFAULT 0,
  `TAGS_LOCK` BOOLEAN NOT NULL DEFAULT 0,
  `BOOK_ID` VARCHAR(255) NOT NULL,
  `ISBN` TEXT NOT NULL,
  `ISBN_LOCK` BOOLEAN NOT NULL DEFAULT 0,
  `LINKS_LOCK` BOOLEAN NOT NULL DEFAULT 0,
  PRIMARY KEY (`BOOK_ID`),
  FOREIGN KEY (`BOOK_ID`) REFERENCES `BOOK` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `BOOK_METADATA_AGGREGATION` (
  `CREATED_DATE` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `LAST_MODIFIED_DATE` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `RELEASE_DATE` DATETIME(6),
  `SUMMARY` TEXT NOT NULL,
  `SUMMARY_NUMBER` TEXT NOT NULL,
  `SERIES_ID` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`SERIES_ID`),
  FOREIGN KEY (`SERIES_ID`) REFERENCES `SERIES` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `BOOK_METADATA_AGGREGATION_AUTHOR` (
  `NAME` TEXT NOT NULL,
  `ROLE` TEXT NOT NULL,
  `SERIES_ID` VARCHAR(255) NOT NULL,
  FOREIGN KEY (`SERIES_ID`) REFERENCES `SERIES` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `BOOK_METADATA_AGGREGATION_TAG` (
  `TAG` TEXT NOT NULL,
  `SERIES_ID` VARCHAR(255) NOT NULL,
  FOREIGN KEY (`SERIES_ID`) REFERENCES `SERIES` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `BOOK_METADATA_AUTHOR` (
  `NAME` TEXT NOT NULL,
  `ROLE` TEXT NOT NULL,
  `BOOK_ID` VARCHAR(255) NOT NULL,
  FOREIGN KEY (`BOOK_ID`) REFERENCES `BOOK` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `BOOK_METADATA_LINK` (
  `LABEL` TEXT NOT NULL,
  `URL` TEXT NOT NULL,
  `BOOK_ID` VARCHAR(255) NOT NULL,
  FOREIGN KEY (`BOOK_ID`) REFERENCES `BOOK` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `BOOK_METADATA_TAG` (
  `TAG` TEXT NOT NULL,
  `BOOK_ID` VARCHAR(255) NOT NULL,
  FOREIGN KEY (`BOOK_ID`) REFERENCES `BOOK` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `CLIENT_SETTINGS_GLOBAL` (
  `KEY` VARCHAR(255) NOT NULL,
  `VALUE` TEXT NOT NULL,
  `ALLOW_UNAUTHORIZED` BOOLEAN NOT NULL DEFAULT 0,
  PRIMARY KEY (`KEY`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `CLIENT_SETTINGS_USER` (
  `USER_ID` VARCHAR(255) NOT NULL,
  `KEY` VARCHAR(255) NOT NULL,
  `VALUE` TEXT NOT NULL,
  PRIMARY KEY (`KEY`, `USER_ID`),
  FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `COLLECTION` (
  `ID` VARCHAR(255) NOT NULL,
  `NAME` TEXT NOT NULL,
  `ORDERED` BOOLEAN NOT NULL DEFAULT 0,
  `SERIES_COUNT` INT NOT NULL,
  `CREATED_DATE` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `LAST_MODIFIED_DATE` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `COLLECTION_SERIES` (
  `COLLECTION_ID` VARCHAR(255) NOT NULL,
  `SERIES_ID` VARCHAR(255) NOT NULL,
  `NUMBER` INT NOT NULL,
  PRIMARY KEY (`COLLECTION_ID`, `SERIES_ID`),
  FOREIGN KEY (`SERIES_ID`) REFERENCES `SERIES` (`ID`),
  FOREIGN KEY (`COLLECTION_ID`) REFERENCES `COLLECTION` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `HISTORICAL_EVENT` (
  `ID` VARCHAR(255) NOT NULL,
  `TYPE` TEXT NOT NULL,
  `BOOK_ID` TEXT,
  `SERIES_ID` TEXT,
  `TIMESTAMP` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `HISTORICAL_EVENT_PROPERTIES` (
  `ID` VARCHAR(255) NOT NULL,
  `KEY` VARCHAR(255) NOT NULL,
  `VALUE` TEXT NOT NULL,
  PRIMARY KEY (`ID`, `KEY`),
  FOREIGN KEY (`ID`) REFERENCES `HISTORICAL_EVENT` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `LIBRARY_EXCLUSIONS` (
  `LIBRARY_ID` VARCHAR(255) NOT NULL,
  `EXCLUSION` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`LIBRARY_ID`, `EXCLUSION`),
  FOREIGN KEY (`LIBRARY_ID`) REFERENCES `LIBRARY` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `MEDIA` (
  `MEDIA_TYPE` TEXT,
  `STATUS` VARCHAR(255) NOT NULL,
  `CREATED_DATE` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `LAST_MODIFIED_DATE` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `COMMENT` TEXT,
  `BOOK_ID` VARCHAR(255) NOT NULL,
  `PAGE_COUNT` INT NOT NULL DEFAULT 0,
  `EXTENSION_CLASS` TEXT,
  `_UNUSED` TEXT,
  `EXTENSION_VALUE_BLOB` LONGBLOB,
  `EPUB_DIVINA_COMPATIBLE` BOOLEAN NOT NULL DEFAULT 0,
  `EPUB_IS_KEPUB` BOOLEAN NOT NULL DEFAULT 0,
  PRIMARY KEY (`BOOK_ID`),
  FOREIGN KEY (`BOOK_ID`) REFERENCES `BOOK` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `MEDIA_FILE` (
  `FILE_NAME` TEXT NOT NULL,
  `BOOK_ID` VARCHAR(255) NOT NULL,
  `MEDIA_TYPE` TEXT,
  `SUB_TYPE` TEXT,
  `FILE_SIZE` INT,
  FOREIGN KEY (`BOOK_ID`) REFERENCES `BOOK` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `MEDIA_PAGE` (
  `FILE_NAME` TEXT NOT NULL,
  `MEDIA_TYPE` TEXT NOT NULL,
  `NUMBER` INT NOT NULL,
  `BOOK_ID` VARCHAR(255) NOT NULL,
  `width` INT,
  `height` INT,
  `FILE_HASH` TEXT NOT NULL,
  `FILE_SIZE` INT,
  PRIMARY KEY (`BOOK_ID`, `NUMBER`),
  FOREIGN KEY (`BOOK_ID`) REFERENCES `BOOK` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `PAGE_HASH` (
  `HASH` VARCHAR(255) NOT NULL,
  `SIZE` INT,
  `ACTION` TEXT NOT NULL,
  `DELETE_COUNT` INT NOT NULL DEFAULT 0,
  `CREATED_DATE` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `LAST_MODIFIED_DATE` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`HASH`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `PAGE_HASH_THUMBNAIL` (
  `HASH` VARCHAR(255) NOT NULL,
  `THUMBNAIL` LONGBLOB NOT NULL,
  PRIMARY KEY (`HASH`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `READLIST` (
  `ID` VARCHAR(255) NOT NULL,
  `NAME` TEXT NOT NULL,
  `BOOK_COUNT` INT NOT NULL,
  `CREATED_DATE` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `LAST_MODIFIED_DATE` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `SUMMARY` TEXT NOT NULL,
  `ORDERED` BOOLEAN NOT NULL DEFAULT 1,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `READLIST_BOOK` (
  `READLIST_ID` VARCHAR(255) NOT NULL,
  `BOOK_ID` VARCHAR(255) NOT NULL,
  `NUMBER` INT NOT NULL,
  PRIMARY KEY (`READLIST_ID`, `BOOK_ID`),
  FOREIGN KEY (`BOOK_ID`) REFERENCES `BOOK` (`ID`),
  FOREIGN KEY (`READLIST_ID`) REFERENCES `READLIST` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `READ_PROGRESS` (
  `BOOK_ID` VARCHAR(255) NOT NULL,
  `USER_ID` VARCHAR(255) NOT NULL,
  `CREATED_DATE` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `LAST_MODIFIED_DATE` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `PAGE` INT NOT NULL,
  `COMPLETED` BOOLEAN NOT NULL,
  `READ_DATE` DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6),
  `device_id` TEXT,
  `device_name` TEXT,
  `locator` LONGBLOB,
  PRIMARY KEY (`BOOK_ID`, `USER_ID`),
  FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`ID`),
  FOREIGN KEY (`BOOK_ID`) REFERENCES `BOOK` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `READ_PROGRESS_SERIES` (
  `SERIES_ID` VARCHAR(255) NOT NULL,
  `USER_ID` VARCHAR(255) NOT NULL,
  `READ_COUNT` INT NOT NULL,
  `IN_PROGRESS_COUNT` INT NOT NULL,
  `MOST_RECENT_READ_DATE` DATETIME(6),
  `LAST_MODIFIED_DATE` DATETIME(6),
  PRIMARY KEY (`SERIES_ID`, `USER_ID`),
  FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`ID`),
  FOREIGN KEY (`SERIES_ID`) REFERENCES `SERIES` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `SERIES_METADATA` (
  `CREATED_DATE` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `LAST_MODIFIED_DATE` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `STATUS` TEXT NOT NULL,
  `STATUS_LOCK` BOOLEAN NOT NULL DEFAULT 0,
  `TITLE` VARCHAR(255) NOT NULL,
  `TITLE_LOCK` BOOLEAN NOT NULL DEFAULT 0,
  `TITLE_SORT` TEXT NOT NULL,
  `TITLE_SORT_LOCK` BOOLEAN NOT NULL DEFAULT 0,
  `SERIES_ID` VARCHAR(255) NOT NULL,
  `PUBLISHER` TEXT NOT NULL,
  `PUBLISHER_LOCK` BOOLEAN NOT NULL DEFAULT 0,
  `READING_DIRECTION` TEXT,
  `READING_DIRECTION_LOCK` BOOLEAN NOT NULL DEFAULT 0,
  `AGE_RATING` INT,
  `AGE_RATING_LOCK` BOOLEAN NOT NULL DEFAULT 0,
  `SUMMARY` TEXT NOT NULL,
  `SUMMARY_LOCK` BOOLEAN NOT NULL DEFAULT 0,
  `LANGUAGE` TEXT NOT NULL,
  `LANGUAGE_LOCK` BOOLEAN NOT NULL DEFAULT 0,
  `GENRES_LOCK` BOOLEAN NOT NULL DEFAULT 0,
  `TAGS_LOCK` BOOLEAN NOT NULL DEFAULT 0,
  `TOTAL_BOOK_COUNT` INT,
  `TOTAL_BOOK_COUNT_LOCK` BOOLEAN NOT NULL DEFAULT 0,
  `SHARING_LABELS_LOCK` BOOLEAN NOT NULL DEFAULT 0,
  `LINKS_LOCK` BOOLEAN NOT NULL DEFAULT 0,
  `ALTERNATE_TITLES_LOCK` BOOLEAN NOT NULL DEFAULT 0,
  PRIMARY KEY (`SERIES_ID`),
  FOREIGN KEY (`SERIES_ID`) REFERENCES `SERIES` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `SERIES_METADATA_ALTERNATE_TITLE` (
  `LABEL` TEXT NOT NULL,
  `TITLE` TEXT NOT NULL,
  `SERIES_ID` VARCHAR(255) NOT NULL,
  FOREIGN KEY (`SERIES_ID`) REFERENCES `SERIES` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `SERIES_METADATA_GENRE` (
  `GENRE` TEXT NOT NULL,
  `SERIES_ID` VARCHAR(255) NOT NULL,
  FOREIGN KEY (`SERIES_ID`) REFERENCES `SERIES` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `SERIES_METADATA_LINK` (
  `LABEL` TEXT NOT NULL,
  `URL` TEXT NOT NULL,
  `SERIES_ID` VARCHAR(255) NOT NULL,
  FOREIGN KEY (`SERIES_ID`) REFERENCES `SERIES` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `SERIES_METADATA_SHARING` (
  `LABEL` TEXT NOT NULL,
  `SERIES_ID` VARCHAR(255) NOT NULL,
  FOREIGN KEY (`SERIES_ID`) REFERENCES `SERIES` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `SERIES_METADATA_TAG` (
  `TAG` TEXT NOT NULL,
  `SERIES_ID` VARCHAR(255) NOT NULL,
  FOREIGN KEY (`SERIES_ID`) REFERENCES `SERIES` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `SERVER_SETTINGS` (
  `KEY` VARCHAR(255) NOT NULL,
  `VALUE` TEXT,
  PRIMARY KEY (`KEY`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `SIDECAR` (
  `URL` VARCHAR(255) NOT NULL,
  `PARENT_URL` TEXT NOT NULL,
  `LAST_MODIFIED_TIME` DATETIME(6) NOT NULL,
  `LIBRARY_ID` TEXT NOT NULL,
  PRIMARY KEY (`URL`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `SYNC_POINT` (
  `ID` VARCHAR(255) NOT NULL,
  `CREATED_DATE` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `USER_ID` VARCHAR(255) NOT NULL,
  `API_KEY_ID` TEXT,
  PRIMARY KEY (`ID`),
  FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `SYNC_POINT_BOOK` (
  `SYNC_POINT_ID` VARCHAR(255) NOT NULL,
  `BOOK_ID` VARCHAR(255) NOT NULL,
  `BOOK_CREATED_DATE` DATETIME(6) NOT NULL,
  `BOOK_LAST_MODIFIED_DATE` DATETIME(6) NOT NULL,
  `BOOK_FILE_LAST_MODIFIED` DATETIME(6) NOT NULL,
  `BOOK_FILE_SIZE` INT NOT NULL,
  `BOOK_FILE_HASH` TEXT NOT NULL,
  `BOOK_METADATA_LAST_MODIFIED_DATE` DATETIME(6) NOT NULL,
  `BOOK_READ_PROGRESS_LAST_MODIFIED_DATE` DATETIME(6),
  `SYNCED` BOOLEAN NOT NULL DEFAULT false,
  `BOOK_THUMBNAIL_ID` TEXT,
  PRIMARY KEY (`SYNC_POINT_ID`, `BOOK_ID`),
  FOREIGN KEY (`SYNC_POINT_ID`) REFERENCES `SYNC_POINT` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `SYNC_POINT_BOOK_REMOVED_SYNCED` (
  `SYNC_POINT_ID` VARCHAR(255) NOT NULL,
  `BOOK_ID` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`SYNC_POINT_ID`, `BOOK_ID`),
  FOREIGN KEY (`SYNC_POINT_ID`) REFERENCES `SYNC_POINT` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `SYNC_POINT_READLIST` (
  `SYNC_POINT_ID` VARCHAR(255) NOT NULL,
  `READLIST_ID` VARCHAR(255) NOT NULL,
  `READLIST_NAME` TEXT NOT NULL,
  `READLIST_CREATED_DATE` DATETIME(6) NOT NULL,
  `READLIST_LAST_MODIFIED_DATE` DATETIME(6) NOT NULL,
  `SYNCED` BOOLEAN NOT NULL DEFAULT false,
  PRIMARY KEY (`SYNC_POINT_ID`, `READLIST_ID`),
  FOREIGN KEY (`SYNC_POINT_ID`) REFERENCES `SYNC_POINT` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `SYNC_POINT_READLIST_BOOK` (
  `SYNC_POINT_ID` VARCHAR(255) NOT NULL,
  `READLIST_ID` VARCHAR(255) NOT NULL,
  `BOOK_ID` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`SYNC_POINT_ID`, `READLIST_ID`, `BOOK_ID`),
  FOREIGN KEY (`SYNC_POINT_ID`) REFERENCES `SYNC_POINT` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `SYNC_POINT_READLIST_REMOVED_SYNCED` (
  `SYNC_POINT_ID` VARCHAR(255) NOT NULL,
  `READLIST_ID` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`SYNC_POINT_ID`, `READLIST_ID`),
  FOREIGN KEY (`SYNC_POINT_ID`) REFERENCES `SYNC_POINT` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `THUMBNAIL_BOOK` (
  `ID` VARCHAR(255) NOT NULL,
  `THUMBNAIL` LONGBLOB,
  `URL` TEXT,
  `SELECTED` BOOLEAN NOT NULL DEFAULT 0,
  `TYPE` TEXT NOT NULL,
  `CREATED_DATE` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `LAST_MODIFIED_DATE` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `BOOK_ID` VARCHAR(255) NOT NULL,
  `WIDTH` INT NOT NULL DEFAULT 0,
  `HEIGHT` INT NOT NULL DEFAULT 0,
  `MEDIA_TYPE` TEXT NOT NULL,
  `FILE_SIZE` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`),
  FOREIGN KEY (`BOOK_ID`) REFERENCES `BOOK` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `THUMBNAIL_COLLECTION` (
  `ID` VARCHAR(255) NOT NULL,
  `SELECTED` BOOLEAN NOT NULL DEFAULT 0,
  `THUMBNAIL` LONGBLOB NOT NULL,
  `TYPE` TEXT NOT NULL,
  `COLLECTION_ID` VARCHAR(255) NOT NULL,
  `CREATED_DATE` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `LAST_MODIFIED_DATE` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `WIDTH` INT NOT NULL DEFAULT 0,
  `HEIGHT` INT NOT NULL DEFAULT 0,
  `MEDIA_TYPE` TEXT NOT NULL,
  `FILE_SIZE` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`),
  FOREIGN KEY (`COLLECTION_ID`) REFERENCES `COLLECTION` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `THUMBNAIL_READLIST` (
  `ID` VARCHAR(255) NOT NULL,
  `SELECTED` BOOLEAN NOT NULL DEFAULT 0,
  `THUMBNAIL` LONGBLOB NOT NULL,
  `TYPE` TEXT NOT NULL,
  `READLIST_ID` VARCHAR(255) NOT NULL,
  `CREATED_DATE` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `LAST_MODIFIED_DATE` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `WIDTH` INT NOT NULL DEFAULT 0,
  `HEIGHT` INT NOT NULL DEFAULT 0,
  `MEDIA_TYPE` TEXT NOT NULL,
  `FILE_SIZE` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`),
  FOREIGN KEY (`READLIST_ID`) REFERENCES `READLIST` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `THUMBNAIL_SERIES` (
  `ID` VARCHAR(255) NOT NULL,
  `URL` TEXT,
  `SELECTED` BOOLEAN NOT NULL DEFAULT 0,
  `THUMBNAIL` LONGBLOB,
  `TYPE` TEXT NOT NULL,
  `CREATED_DATE` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `LAST_MODIFIED_DATE` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `SERIES_ID` VARCHAR(255) NOT NULL,
  `WIDTH` INT NOT NULL DEFAULT 0,
  `HEIGHT` INT NOT NULL DEFAULT 0,
  `MEDIA_TYPE` TEXT NOT NULL,
  `FILE_SIZE` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`),
  FOREIGN KEY (`SERIES_ID`) REFERENCES `SERIES` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `USER_API_KEY` (
  `ID` VARCHAR(255) NOT NULL,
  `USER_ID` VARCHAR(255) NOT NULL,
  `CREATED_DATE` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `LAST_MODIFIED_DATE` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `API_KEY` VARCHAR(255) NOT NULL,
  `COMMENT` TEXT NOT NULL,
  PRIMARY KEY (`ID`),
  FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `USER_LIBRARY_SHARING` (
  `USER_ID` VARCHAR(255) NOT NULL,
  `LIBRARY_ID` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`USER_ID`, `LIBRARY_ID`),
  FOREIGN KEY (`LIBRARY_ID`) REFERENCES `LIBRARY` (`ID`),
  FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `USER_ROLE` (
  `USER_ID` VARCHAR(255) NOT NULL,
  `ROLE` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`USER_ID`, `ROLE`),
  FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `USER_SHARING` (
  `LABEL` VARCHAR(255) NOT NULL,
  `ALLOW` BOOLEAN NOT NULL,
  `USER_ID` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`LABEL`, `ALLOW`, `USER_ID`),
  FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE INDEX `idx__series__created_date` ON `SERIES` (`CREATED_DATE`);
CREATE INDEX `idx__series__last_modified_date` ON `SERIES` (`LAST_MODIFIED_DATE`);
CREATE INDEX `idx__series__library_id` ON `SERIES` (`LIBRARY_ID`);
CREATE INDEX `idx__series_metadata__title` ON `SERIES_METADATA` (`TITLE`);
CREATE INDEX `idx__book__created_date` ON `BOOK` (`CREATED_DATE`);
CREATE INDEX `idx__book__library_id` ON `BOOK` (`LIBRARY_ID`);
CREATE INDEX `idx__book__series_id` ON `BOOK` (`SERIES_ID`);
CREATE INDEX `idx__media_file__book_id` ON `MEDIA_FILE` (`BOOK_ID`);
CREATE INDEX `idx__book_metadata_author__book_id` ON `BOOK_METADATA_AUTHOR` (`BOOK_ID`);
CREATE INDEX `idx__thumbnail_book__file_size` ON `THUMBNAIL_BOOK` (`FILE_SIZE`);
CREATE INDEX `idx__thumbnail_book__height` ON `THUMBNAIL_BOOK` (`HEIGHT`);
CREATE INDEX `idx__thumbnail_book__width` ON `THUMBNAIL_BOOK` (`WIDTH`);
CREATE INDEX `idx__thumbnail_book__book_id` ON `THUMBNAIL_BOOK` (`BOOK_ID`);
CREATE INDEX `idx__media__status` ON `MEDIA` (`STATUS`);
CREATE INDEX `idx__series_metadata_genre__series_id` ON `SERIES_METADATA_GENRE` (`SERIES_ID`);
CREATE INDEX `idx__series_metadata_tag__series_id` ON `SERIES_METADATA_TAG` (`SERIES_ID`);
CREATE INDEX `idx__book_metadata_tag__book_id` ON `BOOK_METADATA_TAG` (`BOOK_ID`);
CREATE INDEX `idx__book_metadata__release_date` ON `BOOK_METADATA` (`RELEASE_DATE`);
CREATE INDEX `idx__book_metadata__number_sort` ON `BOOK_METADATA` (`NUMBER_SORT`);
CREATE INDEX `idx__book_metadata_aggregation_author__series_id` ON `BOOK_METADATA_AGGREGATION_AUTHOR` (`SERIES_ID`);
CREATE INDEX `idx__authentication_activity__user_id` ON `AUTHENTICATION_ACTIVITY` (`USER_ID`);
CREATE INDEX `idx__book_metadata_aggregation_tag__series_id` ON `BOOK_METADATA_AGGREGATION_TAG` (`SERIES_ID`);
CREATE INDEX `idx__thumbnail_series__series_id` ON `THUMBNAIL_SERIES` (`SERIES_ID`);
CREATE INDEX `idx__read_progress__last_modified_date` ON `READ_PROGRESS` (`LAST_MODIFIED_DATE`);
CREATE INDEX `idx__thumbnail_collection__collection_id` ON `THUMBNAIL_COLLECTION` (`COLLECTION_ID`);
CREATE INDEX `idx__thumbnail_readlist__readlist_id` ON `THUMBNAIL_READLIST` (`READLIST_ID`);
CREATE INDEX `idx__book_metadata_link__book_id` ON `BOOK_METADATA_LINK` (`BOOK_ID`);
CREATE INDEX `idx__series_metadata_sharing__series_id` ON `SERIES_METADATA_SHARING` (`SERIES_ID`);
CREATE INDEX `idx__series_metadata_link__series_id` ON `SERIES_METADATA_LINK` (`SERIES_ID`);
CREATE INDEX `idx__series_metadata_alternate_title__series_id` ON `SERIES_METADATA_ALTERNATE_TITLE` (`SERIES_ID`);
CREATE INDEX `idx__library_exclusions__library_id` ON `LIBRARY_EXCLUSIONS` (`LIBRARY_ID`);
CREATE INDEX `idx__user_api_key__user_id` ON `USER_API_KEY` (`USER_ID`);
CREATE INDEX `idx__sync_point__user_id` ON `SYNC_POINT` (`USER_ID`);
CREATE INDEX `idx__sync_point_book_removed_status__sync_point_id` ON `SYNC_POINT_BOOK_REMOVED_SYNCED` (`SYNC_POINT_ID`);
CREATE INDEX `idx__sync_point_book__sync_point_id` ON `SYNC_POINT_BOOK` (`SYNC_POINT_ID`);
CREATE INDEX `idx__sync_point_readlist__sync_point_id` ON `SYNC_POINT_READLIST` (`SYNC_POINT_ID`);
CREATE INDEX `idx__sync_point_readlist_book__sync_point_id_readlist_id` ON `SYNC_POINT_READLIST_BOOK` (`SYNC_POINT_ID`, `READLIST_ID`);
