CREATE TABLE `USER_INVITATION` (
  `ID` VARCHAR(255) NOT NULL,
  `TOKEN_HASH` CHAR(64) NOT NULL,
  `CREATED_BY` VARCHAR(255) NOT NULL,
  `CREATED_DATE` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `EXPIRES_DATE` DATETIME(6) NOT NULL,
  `USED_DATE` DATETIME(6),
  `REVOKED_DATE` DATETIME(6),
  PRIMARY KEY (`ID`),
  UNIQUE KEY `uk_user_invitation_token_hash` (`TOKEN_HASH`),
  FOREIGN KEY (`CREATED_BY`) REFERENCES `USER` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE INDEX `idx_user_invitation_expires_date` ON `USER_INVITATION` (`EXPIRES_DATE`);
