CREATE TABLE `TASK` (
  `ID` VARCHAR(255) NOT NULL,
  `PRIORITY` INT NOT NULL,
  `GROUP_ID` VARCHAR(255),
  `CLASS` TEXT NOT NULL,
  `SIMPLE_TYPE` TEXT NOT NULL,
  `PAYLOAD` TEXT NOT NULL,
  `OWNER` VARCHAR(255),
  `CREATED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `LAST_MODIFIED_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE INDEX `idx__tasks__owner_group_id` ON `TASK` (`OWNER`, `GROUP_ID`);
