export enum SeriesCoverDto {
  FIRST = 'FIRST',
  FIRST_UNREAD_OR_FIRST = 'FIRST_UNREAD_OR_FIRST',
  FIRST_UNREAD_OR_LAST = 'FIRST_UNREAD_OR_LAST',
  LAST = 'LAST',
}

export enum ScanIntervalDto {
  DISABLED = 'DISABLED',
  EVERY_15M = 'EVERY_15M',
  HOURLY = 'HOURLY',
  EVERY_6H = 'EVERY_6H',
  EVERY_12H = 'EVERY_12H',
  DAILY = 'DAILY',
  WEEKLY = 'WEEKLY',
}

export enum SeriesGroupingModeDto {
  DIRECT_PARENT = 'DIRECT_PARENT',
  TOP_LEVEL = 'TOP_LEVEL',
}
